on:
  release:
    types: [created]

permissions:
    contents: write
    packages: write

jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
    - name: Build
      run: go build -v ./...
    - name: Test
      run: go test -v ./...
    - name: Build Release
      env:
        CGO_ENABLED: 1
        GOOS: linux
        GOARCH: amd64
        GH_TOKEN: ${{ github.token }}
      run: |
        go build -o owl-linux-amd64 ./cmd/owl
        gh release upload ${{github.event.release.tag_name}} owl-linux-amd64        
